# Generated by Django 2.2 on 2021-08-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isActive',
            new_name='is_Active',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='isStaff',
            new_name='is_Staff',
        ),
    ]
