# Generated by Django 2.2 on 2021-08-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api2', '0002_auto_20210815_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Staff',
            new_name='is_staff',
        ),
    ]
